apiVersion: apps/v1
kind: Deployment
metadata:
  name: facturacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facturacion
  template:
    metadata:
      labels:
        app: facturacion
    spec:
      containers:
        - name: facturacion
          image: pcastrol/facturacion:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: facturacion-service
spec:
  selector:
    app: facturacion
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
