apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-service
  template:
    metadata:
      labels:
        app: tax-service
    spec:
      containers:
        - name: tax-service
          image: pcastrol/tax-service:latest
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tax-service-service
spec:
  selector:
    app: tax-service
  ports:
    - port: 80
      targetPort: 8081
  type: LoadBalancer
