# CI/CD Pipeline con AKS
name: CI/CD Pipeline - AKS

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Fix permissions (mvnw)
        run: |
          chmod +x facturacion/mvnw
          chmod +x tax-service/mvnw

      - name: Build JAR (facturacion)
        working-directory: facturacion
        run: ./mvnw clean package -DskipTests

      - name: Build JAR (tax-service)
        working-directory: tax-service
        run: ./mvnw clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push facturacion
        uses: docker/build-push-action@v5
        with:
          context: ./facturacion
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/facturacion:latest
            ${{ secrets.DOCKER_USERNAME }}/facturacion:${{ github.sha }}

      - name: Build & Push tax-service
        uses: docker/build-push-action@v5
        with:
          context: ./tax-service
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tax-service:latest
            ${{ secrets.DOCKER_USERNAME }}/tax-service:${{ github.sha }}

      - name: Login en Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Conectar a AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy a Kubernetes
        run: |
          kubectl apply -f k8s/facturacion-deployment.yaml
          kubectl apply -f k8s/tax-service-deployment.yaml
          kubectl set image deployment/facturacion \
            facturacion=${{ secrets.DOCKER_USERNAME }}/facturacion:${{ github.sha }}
          kubectl set image deployment/tax-service \
            tax-service=${{ secrets.DOCKER_USERNAME }}/tax-service:${{ github.sha }}

      - name: Verificar despliegue
        run: |
          kubectl rollout status deployment/facturacion
          kubectl rollout status deployment/tax-service
          kubectl get services
