name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # FACTURACION
      - name: Build JAR (facturacion)
        working-directory: ./facturacion
        run: ./mvnw clean package -DskipTests

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push image (facturacion)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/facturacion:latest ./facturacion
          docker push ${{ secrets.DOCKER_USERNAME }}/facturacion:latest

      # TAX-SERVICE
      - name: Build JAR (tax-service)
        working-directory: ./tax-service
        run: ./mvnw clean package -DskipTests

      - name: Build & Push image (tax-service)
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tax-service:latest ./tax-service
          docker push ${{ secrets.DOCKER_USERNAME }}/tax-service:latest
